package com.jwdfhi.meal_up.models

data class RandomMealServiceModel(
    val meals: List<Meal>
) {
    data class Meal(
        var isLiked: Boolean = false,
        var isMarked: Boolean = false,
        var markColor: String?,
        var markName: String?,

        val dateModified: Any,
        val idMeal: String,
        val strArea: String,
        val strCategory: String,
        val strCreativeCommonsConfirmed: Any,
        val strDrinkAlternate: Any,
        val strImageSource: Any,
        val strIngredient1: String,
        val strIngredient10: Any,
        val strIngredient11: Any,
        val strIngredient12: Any,
        val strIngredient13: Any,
        val strIngredient14: Any,
        val strIngredient15: Any,
        val strIngredient16: Any,
        val strIngredient17: Any,
        val strIngredient18: Any,
        val strIngredient19: Any,
        val strIngredient2: String,
        val strIngredient20: Any,
        val strIngredient3: String,
        val strIngredient4: String,
        val strIngredient5: String,
        val strIngredient6: String,
        val strIngredient7: String,
        val strIngredient8: String,
        val strIngredient9: Any,
        val strInstructions: String,
        val strMeal: String,
        val strMealThumb: String,
        val strMeasure1: String,
        val strMeasure10: String,
        val strMeasure11: String,
        val strMeasure12: String,
        val strMeasure13: String,
        val strMeasure14: String,
        val strMeasure15: String,
        val strMeasure16: String,
        val strMeasure17: String,
        val strMeasure18: String,
        val strMeasure19: String,
        val strMeasure2: String,
        val strMeasure20: String,
        val strMeasure3: String,
        val strMeasure4: String,
        val strMeasure5: String,
        val strMeasure6: String,
        val strMeasure7: String,
        val strMeasure8: String,
        val strMeasure9: String,
        val strSource: String,
        val strTags: String,
        val strYoutube: String
    )
}